[package]
name = "project-bazaar"
version = "0.1.0"
edition = "2021"

[lib]
# Change this to point to the standard src folder
path = "src/lib.rs"

[dependencies]
# Leave this empty for now to clear all external errors